version: '3'
services:
  graph-node-write:
    image: graphprotocol/graph-node:v0.27.0
    depends_on:
      - ipfs
      - postgres
    ports:
      - '8020:8020'
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: ${postgres_pass}
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      # Change next line if you want to connect to a different JSON-RPC endpoint
      ethereum: '{{node.network}}:{{& node.address}}'
      GRAPH_LOG: '{{node.log_level}}'
      GRAPH_GRAPHQL_QUERY_TIMEOUT: '10'
      GRAPH_SQL_STATEMENT_TIMEOUT: '10'
      GRAPH_GRAPHQL_MAX_DEPTH: '16'
      GRAPH_GRAPHQL_MAX_COMPLEXITY: '1500000'
  ipfs:
    image: ipfs/go-ipfs:v0.11.0
    ports:
      - '5001:5001'
    expose:
      - 5001
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
