---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "graphql-read.labels" . | nindent 4 }}
  name: {{ include "graphql-read.fullname" . }}-envs
data:
{{ toYaml .Values.envs | indent 2 }}
