---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphql-read.fullname" . }}-http
  labels:
    {{- include "graphql-read.labels" . | nindent 4 }}-http
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graphql-read.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphql-read.fullname" . }}-ws
  labels:
    {{- include "graphql-read.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ws.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graphql-read.selectorLabels" . | nindent 4 }}
